application: nearby-pets
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: webroot/css

- url: /img
  static_dir: webroot/img

- url: /js
  static_dir: webroot/js

- url: /favicon\.ico
  static_files: webroot/favicon.ico
  upload: webroot/favicon.ico

- url: /.*
  script: index.php

env_variables:
  # Uncomment the following to enable debug mode.
  CAKEPHP_DEBUG: '1'

  # If connecting via TCP/IP to Google Cloud SQL
  PROD_DB_HOSTNAME: "104.155.27.238"
  PROD_DB_PORT: "3306"

  # If connecting via App Engine to Google Cloud SQL
  PROD_DB_UNIXSOCKET: "/cloudsql/nearby-pets:europe-west1:mytestinstance"
  PROD_DB_USERNAME: "root"
  PROD_DB_PASSWORD: ""
  PROD_DB_DATABASE: "nearby_pets_db"

  # Change below to match your settings for local development.

  # If connecting to MySQL using TCP/IP
  DEV_DB_HOSTNAME: "104.155.27.238"
  DEV_DB_PORT: "3306"

  # If connecting to MySQL using sockets.
  #DEV_DB_UNIXSOCKET: "/cloudsql/nearby-pets:europe-west1:mytestinstance"
  DEV_DB_USERNAME: "root"
  DEV_DB_PASSWORD: ""
  DEV_DB_DATABASE: "nearby_pets_db"
